export const official = "https://kal.kerala.gov.in";
export const galleryPhotos = [
  {
    image: "gallery-1",
    alt: "Visitors exchanging a potted plant at the KAL factory",
    caption: "A welcome at the KAL factory",
  },
  {
    image: "gallery-2",
    alt: "A blue KAL electric three-wheeler on display at a dealership",
    caption: "KAL electric mobility on display",
  },
  {
    image: "gallery-3",
    alt: "A visitor greeting a representative outside the KAL building",
    caption: "Visitors at KAL",
  },
  {
    image: "gallery-4",
    alt: "A group welcoming a visitor with flowers outside the KAL factory",
    caption: "A gathering at the factory",
  },
  {
    image: "gallery-5",
    alt: "KAL representatives welcoming a visitor outside the factory entrance",
    caption: "Meeting the people behind KAL",
  },
];
export const products = [
  {
    slug: "kerala-neem-g",
    name: "Kerala Neem G",
    category: "passenger",
    label: "Passenger mobility",
    image: "neem-g",
    description:
      "An all-electric three-wheeler for everyday passenger journeys.",
    length: "2,540 mm",
    weight: "626 kg",
    torque: "55.3 Nm",
    range: "90–100 km",
    capacity: "Driver + 3 passengers",
    speed: "40–45 km/h",
    charge: "3 hrs 55 min",
    battery: "60 V LiFePO₄",
    power: "2.2 kW",
    intro:
      "Built for everyday public transport, Kerala Neem G combines electric propulsion with space for a driver and three passengers. Its direct-drive motor and lithium iron phosphate battery support practical, low-maintenance mobility.",
  },
  {
    slug: "kerala-green-stream-e-cart",
    name: "Kerala Green Stream",
    category: "goods",
    label: "Goods transportation",
    image: "green-stream",
    description:
      "Compact electric cargo transport for local businesses and communities.",
    length: "2,800 mm",
    weight: "679 kg",
    torque: "23.93 Nm",
    range: "100–130 km",
    capacity: "1 driver · up to 310 kg load",
    speed: "25 km/h",
    charge: "4–5 hours",
    battery: "48 V LFP · 4.8 kWh",
    power: "1.5 kW",
    intro:
      "Kerala Green Stream is an electric cart designed for goods transportation and urban utility work. Its narrow width helps it navigate tight roads, while electric propulsion supports quieter, emission-free operation at the vehicle.",
  },
  {
    slug: "e-cart-with-garbage-box-having-dry-and-wet-compartments-hydraulic-tipping-mechanism",
    name: "Waste collection E-Cart",
    category: "utility",
    label: "Municipal utility",
    image: "garbage-cart",
    description: "Separate dry and wet compartments with hydraulic tipping.",
    length: "2,800 mm",
    weight: "679 kg",
    torque: "23.93 Nm",
  },
  {
    slug: "e-cart-with-canopy",
    name: "E-Cart with canopy",
    category: "goods",
    label: "Covered goods transport",
    image: "canopy-cart",
    description: "An electric goods cart with a protective canopy.",
    length: "2,800 mm",
    weight: "679 kg",
    torque: "23.93 Nm",
  },
  {
    slug: "e-cart-with-carriage-box-hydraulic-tipping-mechanism",
    name: "Hydraulic tipping E-Cart",
    category: "utility",
    label: "Municipal utility",
    image: "tipping-cart",
    description:
      "A carriage box and hydraulic tipping mechanism for utility work.",
    length: "2,800 mm",
    weight: "679 kg",
    torque: "23.93 Nm",
  },
  {
    slug: "kal-mini-e-cart",
    name: "KAL Mini E-Cart",
    category: "goods",
    label: "Compact cargo mobility",
    image: "mini-cart",
    description: "A compact electric cart for everyday local transport.",
    length: "2,440 mm",
    weight: "360 kg",
    torque: "11 Nm",
  },
  {
    slug: "kal-ice-cream-e-cart",
    name: "Ice cream E-Cart",
    category: "utility",
    label: "Mobile vending",
    image: "ice-cream-cart",
    description: "Electric mobility designed for mobile ice cream vending.",
    length: "2,800 mm",
    weight: "725 kg",
    torque: "23.93 Nm",
  },
  {
    slug: "kal-electric-buggy",
    name: "KAL Electric Buggy",
    category: "passenger",
    label: "Campus mobility",
    image: "electric-buggy",
    description:
      "Electric passenger transport for campuses and enclosed spaces.",
    length: "2,780 mm",
    weight: "665 kg",
    torque: "23.93 Nm",
  },
  {
    slug: "kal-mini-e-cart-plus",
    name: "KAL Mini E-Cart Plus",
    category: "goods",
    label: "Goods transportation",
    image: "mini-cart-plus",
    description: "A versatile electric cart for goods and local delivery.",
    length: "2,800 mm",
    weight: "635 kg",
    torque: "23.93 Nm",
  },
];
export const searchItems = [
  ...products.map((p) => ({
    title: p.name,
    detail: p.label,
    url: `/products/${p.slug}/`,
  })),
  {
    title: "About Kerala Automobiles Limited",
    detail: "Our history, purpose and leadership",
    url: "/about/",
  },
  {
    title: "Manufacturing & aerospace",
    detail: "Facilities and precision engineering",
    url: "/manufacturing/",
  },
  {
    title: "Tenders, RTI & disclosures",
    detail: "Public information and government links",
    url: "/public-information/",
  },
  {
    title: "News & careers",
    detail: "Notifications and recruitment",
    url: "/news/",
  },
  {
    title: "Contact & sales enquiry",
    detail: "Sales, support and office address",
    url: "/contact/",
  },
  { title: "Photo gallery", detail: "From the KAL gallery", url: "/gallery/" },
];
